import { ContactoOrbital } from '../modelos/contacto-orbital.model';

export const contactosOrbitales: readonly ContactoOrbital[] = [
  {
    id: 'github',
    nombre: 'GitHub',
    icono: 'assets/imagenes/github.png',
    tipo: 'enlace',
    url: 'https://github.com/xNaty15',
    ariaLabel: 'Abrir GitHub de Nathalia en una pestaña nueva',
    tooltip: 'GitHub',
    anguloInicial: -92,
    anguloCompensado: 92,
    duracion: '28s',
  },
  {
    id: 'instagram',
    nombre: 'Instagram',
    icono: 'assets/imagenes/instagram.png',
    tipo: 'enlace',
    url: 'https://www.instagram.com/nath_pzlz/',
    ariaLabel: 'Abrir Instagram de Nathalia en una pestaña nueva',
    tooltip: 'Instagram',
    anguloInicial: -18,
    anguloCompensado: 18,
    duracion: '31s',
  },
  {
    id: 'whatsapp',
    nombre: 'WhatsApp',
    icono: 'assets/imagenes/what.png',
    tipo: 'enlace',
    url: 'https://wa.me/50492664604',
    ariaLabel: 'Abrir WhatsApp para contactar a Nathalia',
    tooltip: 'WhatsApp',
    anguloInicial: 58,
    anguloCompensado: -58,
    duracion: '29s',
  },
  {
    id: 'discord',
    nombre: 'Discord',
    icono: 'assets/imagenes/discord.png',
    tipo: 'copiar',
    valorCopiable: 'xkatylinux',
    ariaLabel: 'Copiar usuario de Discord xkatylinux',
    tooltip: 'Copiar Discord',
    anguloInicial: 145,
    anguloCompensado: -145,
    duracion: '33s',
  },
  {
    id: 'gmail',
    nombre: 'Gmail',
    icono: 'assets/imagenes/gmail.png',
    tipo: 'pendiente',
    ariaLabel: 'Gmail pendiente: correo próximamente',
    tooltip: 'Correo próximamente',
    anguloInicial: 222,
    anguloCompensado: -222,
    duracion: '30s',
  },
];
