import { ContactoOrbital } from '../modelos/contacto-orbital.model';

export const contactosOrbitales: readonly ContactoOrbital[] = [
  {
    id: 'github',
    nombre: 'GitHub',
    icono: 'assets/imagenes/github.png',
    tipo: 'enlace',
    url: 'https://github.com/xNaty15',
    ariaLabel: 'Abrir GitHub de Nathalia en una pestaña nueva',
    tooltip: 'GitHub',
    retrasoAnimacion: '0s',
  },
  {
    id: 'instagram',
    nombre: 'Instagram',
    icono: 'assets/imagenes/instagram.png',
    tipo: 'enlace',
    url: 'https://www.instagram.com/nath_pzlz/',
    ariaLabel: 'Abrir Instagram de Nathalia en una pestaña nueva',
    tooltip: 'Instagram',
    retrasoAnimacion: '-3.6s',
  },
  {
    id: 'whatsapp',
    nombre: 'WhatsApp',
    icono: 'assets/imagenes/what.png',
    tipo: 'enlace',
    url: 'https://wa.me/50492664604',
    ariaLabel: 'Abrir WhatsApp para contactar a Nathalia',
    tooltip: 'WhatsApp',
    retrasoAnimacion: '-7.2s',
  },
  {
    id: 'discord',
    nombre: 'Discord',
    icono: 'assets/imagenes/discord.png',
    tipo: 'copiar',
    valorCopiable: 'xkatylinux',
    ariaLabel: 'Copiar usuario de Discord xkatylinux',
    tooltip: 'Copiar Discord',
    retrasoAnimacion: '-10.8s',
  },
  {
    id: 'gmail',
    nombre: 'Gmail',
    icono: 'assets/imagenes/gmail.png',
    tipo: 'pendiente',
    ariaLabel: 'Gmail pendiente: correo próximamente',
    tooltip: 'Correo próximamente',
    retrasoAnimacion: '-14.4s',
  },
];
